
default_param_dicts = {
    "famnist": {
        "dataset": ["famnist"],
        "split": ["dirichlet"],
        "dir_alpha": [None],
        "n_classes": [10],
        "n_clients": [None],
        "n_max_sam": [None],
        "c_ratio": [None],
        "net": [None],
        "max_round": [None],
        "test_round": [None],
        "local_epochs": [None],
        "local_steps": [None],
        "batch_size": [64],
        "optimizer": ["SGD"],
        "lr": [0.03],
        "momentum": [0.9],
        "weight_decay": [1e-5],
        "max_grad_norm": [100.0],
        "cuda": [True],
    },
    "cifar10": {
        "dataset": ["cifar10"],
        "split": ["dirichlet"],
        "dir_alpha": [None],
        "n_classes": [10],
        "n_clients": [None],
        "n_max_sam": [None],
        "c_ratio": [None],
        "net": [None],
        "max_round": [None],
        "test_round": [None],
        "local_epochs": [None],
        "local_steps": [None],
        "batch_size": [64],
        "optimizer": ["SGD"],
        "lr": [0.03],
        "momentum": [0.9],
        "weight_decay": [1e-5],
        "max_grad_norm": [100.0],
        "cuda": [True],
    },
    "cifar100": {
        "dataset": ["cifar100"],
        "split": ["dirichlet"],
        "dir_alpha": [None],
        "n_classes": [100],
        "n_clients": [None],
        "n_max_sam": [None],
        "c_ratio": [None],
        "net": [None],
        "max_round": [None],
        "test_round": [None],
        "local_epochs": [None],
        "local_steps": [None],
        "batch_size": [64],
        "optimizer": ["SGD"],
        "lr": [0.03],
        "momentum": [0.9],
        "weight_decay": [1e-5],
        "max_grad_norm": [100.0],
        "cuda": [True],
    },
}
